project_id = "spgusjrjrhfychhdwixn"

[functions.sitemap]
verify_jwt = false

[functions.share-preview]
verify_jwt = false

[functions.rss-feed]
verify_jwt = false

[functions.ads-txt]
verify_jwt = false

[functions.news-api]
verify_jwt = false