name: Maintainer PR
on:
workflow_dispatch:
inputs:
branch:
description: 'Branch base (ex: main)'
default: 'main'
patch:
description: 'Patch unified diff (git apply)'
required: true
jobs:
apply:
runs-on: ubuntu-latest
permissions:
contents: write
pull-requests: write
steps:
- uses: actions/checkout@v4
with:
fetch-depth: 0
- name: Config git
run: |
git config user.name "github-actions[bot]"
git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
- name: Criar branch e aplicar patch
run: |
BRANCH="maint/${{ github.run_id }}"
git checkout -b "$BRANCH"
printf '%s\n' "${{ github.event.inputs.patch }}" > /tmp/patch.diff
git apply --whitespace=fix /tmp/patch.diff
git add -A
git commit -m "chore: apply maintainer patch"
git push origin "$BRANCH"
- name: Abrir PR
uses: actions/github-script@v7
with:
script: |
const branch = maint/${{ github.run_id }};
const base = '${{ github.event.inputs.branch }}';
await github.rest.pulls.create({
owner: context.repo.owner,
repo: context.repo.repo,
title: Maintainer patch ${{ github.run_id }},
head: branch,
base,
body: 'Aplicação de patch enviada por workflow_dispatch.'
});
