name: Maintainer PR
on:
workflow_dispatch:
inputs:
branch:
description: 'Branch base (ex: main)'
default: 'main'
patch:
description: 'Patch unified diff (git apply)'
required: true
jobs:
apply:
runs-on: ubuntu-latest
permissions:
contents: write
pull-requests: write
steps:
- uses: actions/checkout@v4
with:
fetch-depth: 0
- name: Config git
run: |
git config user.name "github-actions[bot]"
git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
- name: Criar branch e aplicar patch
run: |
BRANCH="maint/${{ github.run_id }}"
git checkout -b "$BRANCH"
printf '%s\n' "${{ github.event.inputs.patch }}" > /tmp/patch.diff
git apply --whitespace=fix /tmp/patch.diff
git add -A
git commit -m "chore: apply maintainer patch"
git push origin "$BRANCH"
- name: Abrir PR
uses: actions/github-script@v7
with:
script: |
const branch = maint/${{ github.run_id }};
const base = ${{ github.event.inputs.branch }};
await github.pulls.create({
owner: context.repo.owner,
repo: context.repo.repo,
title: Maintainer patch ${{ github.run_id }},
head: branch,
base,
body: "Aplicação de patch enviada por workflow_dispatch."
});
Disparar o workflow com o patch

Vá em Actions → Maintainer PR → Run workflow
Branch: main
Patch: cole o diff abaixo e clique em “Run workflow”
Patch (corrige lazy do DynamicCategoryRoute e remove “Carregando...”)
--- a/src/App.tsx
+++ b/src/App.tsx
@@
-import { BrowserRouter, Routes, Route } from "react-router-dom";
-import { Suspense, lazy } from "react";
+import { BrowserRouter, Routes, Route } from "react-router-dom";
+import { Suspense, lazy } from "react";
@@
-const DynamicCategoryRoute = lazy(() => import("./components/DynamicCategoryRoute")).then(m => ({ default: m.DynamicCategoryRoute }));
+const DynamicCategoryRoute = lazy(() =>

import("./components/DynamicCategoryRoute").then(m => ({ default: m.DynamicCategoryRoute }))
+);
@@
   <BrowserRouter>
     <Suspense fallback={<div className="p-6">Carregando...</div>}>
   <BrowserRouter>
     <Suspense fallback={null}>
       <Routes>
         <Route path="/" element={<Index />} />
         <Route path="/auth" element={<Auth />} />
         <Route path="/perfil" element={
           <ProtectedRoute>
             <Profile />
           </ProtectedRoute>
         } />
         <Route path="/admin" element={
           <ProtectedRoute requiredRole="redator">
             <ModernAdmin />
           </ProtectedRoute>
         } />
         <Route path="/admin/configuracoes" element={
           <ProtectedRoute requiredRole="admin">
             <SiteConfigurations />
           </ProtectedRoute>
         } />
         <Route path="/search" element={<Search />} />
         <Route path="/busca" element={<Search />} />
         <Route path="/ao-vivo" element={<AoVivo />} />
         <Route path="/videos" element={<Videos />} />
         <Route path="/contato" element={<Contact />} />
         <Route path="/anuncie" element={<Advertise />} />
         <Route path="/ads.txt" element={<AdsTxt />} />
         <Route path="/robots.txt" element={<RobotsTxt />} />
         <Route path="/sitemap.xml" element={<Sitemap />} />
         <Route path="/noticia/:id" element={<NewsArticle />} />
         <Route path="/:categorySlug/:slug" element={<NewsArticle />} />
         <Route path="/:categorySlug/:slug/:id" element={<NewsArticle />} />
         {/* Rota dinâmica para todas as categorias */}
         <Route path="/:categorySlug" element={<DynamicCategoryRoute />} />
         {/* ADD ALL CUSTOM ROUTES ABOVE THE CATCH-ALL "*" ROUTE */}
         <Route path="*" element={<NotFound />} />
       </Routes>
     </Suspense>
     </Suspense>
   </BrowserRouter>
